### ISSUE TITLE
Navbar OverFlow

### ISSUE THREAD

**Issue by Omkar-Sonawane-23** [Omkar-Sonawane-23/VedicVani#10]
![image](https://github.com/Omkar-Sonawane-23/VedicVani/assets/130058150/d1860c97-85a5-4599-ba46-7fc26df1859b)
The Content Of Website is Going Above the Navbar On Scroll

How To Solve:
- Increse Navbars Z-index 
- Disable Scrolling On HomePage

**Comment by shivamb11** [comment]
Hello, I can solve this issue. May I work on this ?

**Comment by Omkar-Sonawane-23** [comment]
@shivamb11 Happy Coding Bro!!

**Comment by shivamb11** [comment]
@Omkar-Sonawane-23 Can you please add **gssoc** label and the **level** label to it ?

**Comment by dhairyagothi** [comment]
it is not fixed till now please assign to me
@Omkar-Sonawane-23
