### ISSUE TITLE
[BUG]: Page not responsive

### ISSUE THREAD

**Issue by aryansharma220** [Omkar-Sonawane-23/VedicVani#107]
**Describe the bug**
The page is not responsive in smaller screens

**To Reproduce**
1. Go to HomePage in responsive mode

**Expected behavior**
Page should be responsive on small screens
**Screenshots**
I
![image](https://github.com/Omkar-Sonawane-23/VedicVani/assets/133234867/098ff106-970b-4182-99ff-eea5277084de)

**Desktop (please complete the following information):**
 - Windows 10
 - Edge

**Comment by sameer-soni** [comment]
duplicate #123
