### ISSUE TITLE
Button UI

### ISSUE THREAD

**Issue by traptijindal** [Omkar-Sonawane-23/VedicVani#108]
We can add hover effect and other effects to buttons to make the ui look good .Please assign this issue to me.
![Screenshot 2024-05-15 002058](https://github.com/Omkar-Sonawane-23/VedicVani/assets/130233959/3f77fb08-6aa3-450a-be1b-c78bff2a9983)

**Comment by sameer-soni** [comment]
@traptijindal assigning this to you, add a cool hover effect👍

**Comment by traptijindal** [comment]
Hey! @Omkar-Sonawane-23 .Please close this issue as I have resolved this issue .
![Screenshot 2024-05-15 182845](https://github.com/Omkar-Sonawane-23/VedicVani/assets/130233959/92c98c9a-f8c0-4d81-bce0-4365cd9dcc56)
![Screenshot 2024-05-15 182826](https://github.com/Omkar-Sonawane-23/VedicVani/assets/130233959/95725898-9a22-48cf-87e5-08fc84e7efec)


![Screenshot 2024-05-15 182902](https://github.com/Omkar-Sonawane-23/VedicVani/assets/130233959/e2bc8276-c7e6-4eeb-afe0-1136d37afc9a)
