### ISSUE TITLE
Change UI of about page

### ISSUE THREAD

**Issue by traptijindal** [Omkar-Sonawane-23/VedicVani#109]
We can improve the UI of about section..Please assign this task to me. I would like to contribute in this issue.
![Screenshot 2024-05-15 002322](https://github.com/Omkar-Sonawane-23/VedicVani/assets/130233959/979d9747-cb7f-43f6-bae1-373636eea9a6)

**Comment by sameer-soni** [comment]
@traptijindal okay, assigning it to you.

**Comment by Manaswini123456** [comment]
@sameer-soni Kindly assign this issue to me. As a full stack developer, I have the comprehensive knowledge and expertise required to handle it effectively.

**Comment by traptijindal** [comment]
Hey! @sameer-soni @Omkar-Sonawane-23 . I have resolved this issue .Please review my pull request #147.
