### ISSUE TITLE
we can add animation in the site

### ISSUE THREAD

**Issue by kaushik-2318** [Omkar-Sonawane-23/VedicVani#118]
We can add a onload animation , smooth scrolling and many more animation. That's make website more dynamic and enhance the user interaction.
We can add Carousel. UI/UX need to enhance.
 
# Assign Me. I can do That.
eg:- https://portfolio-six-teal-24.vercel.app/

**Comment by sameer-soni** [comment]
@kaushik-2318 go ahead, implement good animations and if we would like it, we will merge your pr.

**Comment by kaushik-2318** [comment]
> @kaushik-2318 go ahead, implement good animations and if we would like it, we will merge your pr.

Okay, I will do my Best.

**Comment by kaushik-2318** [comment]
okay, I will do my best
