### ISSUE TITLE
Arrows are not perfect

### ISSUE THREAD

**Issue by suraj-9849** [Omkar-Sonawane-23/VedicVani#124]
![image](https://github.com/Omkar-Sonawane-23/VedicVani/assets/146669517/3de642c1-c109-4e7f-8f10-5567fd820d9f)

Imporving the Arrow button.
I would like to work on this issue please assign this to me under @gssoc'24 @sameer-soni

**Comment by sameer-soni** [comment]
@suraj-9849 okay, assigning this you. Try to improve it.

**Comment by suraj-9849** [comment]
@sameer-soni ,This was fixed in the responsive issue only. U can close this issue I fixed the arrow in the Responsive issue only #123
