### ISSUE TITLE
shlokas other than chapter 1 are not found

### ISSUE THREAD

**Issue by nagamukesh** [Omkar-Sonawane-23/VedicVani#127]
Describe the bug
chapter summary is not changing/updated according to the changed chapter

To Reproduce

1)Go to website
2)change the chapter number (other than 1) and click on the read shlokas
3)See error(you will see the same shlokas as chapter 1)

Expected behavior
appropriate shlokas for each chapter of Bhagavadgita

I can add all the shlokas of each chapter from some trusted sources like Gita Press English and Hindi translations of Bhagavad Gita etc and make it functioning
please assign this issue to me under gssoc 2024

**Comment by sameer-soni** [comment]
@nagamukesh, I changed the chapter number and I'm getting different shloks.
![Screenshot 2024-05-17 115315](https://github.com/Omkar-Sonawane-23/VedicVani/assets/134498717/e78629a8-7656-4d2b-80cc-76372ae23644)
![Screenshot 2024-05-17 115330](https://github.com/Omkar-Sonawane-23/VedicVani/assets/134498717/20cf9c46-2d60-418d-a334-6b5f87de0d34)
