### ISSUE TITLE
[Feature] : Implement the Contact Page

### ISSUE THREAD

**Issue by sivaprasath2004** [Omkar-Sonawane-23/VedicVani#140]
**Is your feature request related to a problem? Please describe.**
- In this project doesn't `contact` page available.
- so If i can implement the new page of the `contact` paging.

**Describe the solution you'd like**
- In every website important page `contact`.
- That's not available in the project.
- I am ready to work in this project.
- please assign me..

**Comment by sameer-soni** [comment]
@sivaprasath2004 okay assigning this to you.

**Comment by Manaswini123456** [comment]
@sameer-soni Kindly assign this issue to me. As a full stack developer, I have the comprehensive knowledge and expertise required to handle it effectively.
