### ISSUE TITLE
Chapters's Summary Wrongly Written 

### ISSUE THREAD

**Issue by namandude** [Omkar-Sonawane-23/VedicVani#141]
There is mistake in spelling of chapter summary , also the color theme not attractive . 

![image](https://github.com/Omkar-Sonawane-23/VedicVani/assets/118013565/4c5f7415-b14a-4ef3-a4ce-7c37c719da01)

We can correct the spelling and make the hover effect more smooth .

**Comment by sameer-soni** [comment]
@namandude looks correct to me.
![Screenshot 2024-05-17 185738](https://github.com/Omkar-Sonawane-23/VedicVani/assets/134498717/82dfecf5-efec-4a5f-94c3-fa572f698bdc)
