### ISSUE TITLE
Go back Routing

### ISSUE THREAD

**Issue by Hemashree21** [Omkar-Sonawane-23/VedicVani#144]
When we click on a certain chapter and want to go back to the home page, we have to manually press the back arrow button in the topbar to go to home page or press the home in header. It will be better to add the back button inside each chapter.

![image](https://github.com/Omkar-Sonawane-23/VedicVani/assets/138188163/8bbd915b-5b8e-4bdf-80e8-12a3902fa04a)

@Omkar-Sonawane-23 please assign this issue to me

**Comment by sameer-soni** [comment]
@Hemashree21 You can also click the logo to go back to home button. This change feels unnecessary, thanks for you suggestion though.
