### ISSUE TITLE
improving resource page cards.

### ISSUE THREAD

**Issue by traptijindal** [Omkar-Sonawane-23/VedicVani#148]
Hey! @Omkar-Sonawane-23 . Please assign me this task under GSoC24.

I will assure you that I will put my best efforts to make this page look good.

![Screenshot 2024-05-17 232414](https://github.com/Omkar-Sonawane-23/VedicVani/assets/130233959/e69558aa-0dff-4f60-adeb-99112ef7dea8)

**Comment by sameer-soni** [comment]
@traptijindal okay, assigning it to you
