### ISSUE TITLE
[BUG] : Proper alignment of title

### ISSUE THREAD

**Issue by PranotiPD** [Omkar-Sonawane-23/VedicVani#154]
**Describe the bug**
Proper alignment of the title should be there.

![Screenshot (764)](https://github.com/Omkar-Sonawane-23/VedicVani/assets/97724414/195ddbab-b7b2-42d8-afdf-531f130080a5)

some part of the title is hiding under the header.

I would like to fix it.

**Comment by sameer-soni** [comment]
@PranotiPD assigned

**Comment by PranotiPD** [comment]
someone already worked on it so closing issue @sameer-soni
