### ISSUE TITLE
Navbar ui design  changing

### ISSUE THREAD

**Issue by MaragathaMeenakshi** [Omkar-Sonawane-23/VedicVani#160]
**Is your feature request related to a problem? Please describe.**
Making Navbar UI better

**Describe the solution you'd like**
We can do like this.

https://github.com/Omkar-Sonawane-23/VedicVani/assets/113226919/dd335967-d009-4c63-9f08-eb57309ac83b

I like to work on this . Assign me.

**Comment by sameer-soni** [comment]
@MaragathaMeenakshi Navbar's color is not matching with the theme.

**Comment by MaragathaMeenakshi** [comment]
![Screenshot 2024-05-18 235112](https://github.com/Omkar-Sonawane-23/VedicVani/assets/113226919/f13a7b29-d615-4000-b0e2-945c84f64d6d)

I will change the color.
is that text and contact us button is okey.

**Comment by sameer-soni** [comment]
@MaragathaMeenakshi yeah it is better, add more horizontal padding in contact us and you can try with different fonts if you want to. assigning it you, just change it's color scheme to match with orange.

**Comment by MaragathaMeenakshi** [comment]
okey, I will make changes. Thank you for your suggestion @sameer-soni

**Comment by MaragathaMeenakshi** [comment]
@sameer-soni  could you assign me?

**Comment by MaragathaMeenakshi** [comment]
I could not find my name in assignees . @sameer-soni could you assign me.
