### ISSUE TITLE
Redesigning the Resource Page also adding responsiveness to this Page

### ISSUE THREAD

**Issue by suraj-9849** [Omkar-Sonawane-23/VedicVani#161]
![image](https://github.com/Omkar-Sonawane-23/VedicVani/assets/146669517/4470c942-e3b9-4845-ba84-f4ccf4d259d4)
I thought The content present in the resource page is not related to the website so I would like to redesign keep the resources like bhagavad gita
Ramayan
etc.. 
So can you please assign this to me under @gssoc @sameer-soni

**Comment by sameer-soni** [comment]
@suraj-9849 That's a nice idea, go ahead.

**Comment by suraj-9849** [comment]
https://github.com/Omkar-Sonawane-23/VedicVani/assets/146669517/be108ab1-5e85-4df2-b680-600203361683
@sameer-soni  if this is ok Then I will make the PR I also made it responsive

**Comment by suraj-9849** [comment]
https://github.com/Omkar-Sonawane-23/VedicVani/assets/146669517/ae3f6bdf-e57b-4a66-b648-31206890159a

**Comment by suraj-9849** [comment]
https://github.com/Omkar-Sonawane-23/VedicVani/assets/146669517/fce39968-78de-4a66-8012-93e70c52fba5



Is this ok @sameer-soni I also made it responsive
