### ISSUE TITLE
Go button on Home page not in alignment by the other input boxes

### ISSUE THREAD

**Issue by haseebzaki-07** [Omkar-Sonawane-23/VedicVani#238]
**Describe the bug**
The go button on the home page should ideally be in the alignment of the other two input boxes for a clean user experience

**To Reproduce**
1. Go to Home page 
2. Scroll down to Input boxes
3. See distorted alignment of the go button

**Expected behavior**
The Go button should ideally be in the alignment of the other two input boxes for a clean user experience

**Screenshots**
![Screenshot 2024-07-29 234446](https://github.com/user-attachments/assets/4683f658-7be8-4fa8-9c6c-27ca6f150fb5)

**Comment by ParasY1724** [comment]
Please assign this task to me under gssoc-ext24.
