### ISSUE TITLE
Improve UI for navbar and dropdowns

### ISSUE THREAD

**Issue by Sudhan22z265** [Omkar-Sonawane-23/VedicVani#33]
**Is your feature request related to a problem? Please describe.**
Users are encountering difficulties with the current user interface (UI) for the navbar and dropdown menus, leading to confusion and inefficiency in navigation.

**Describe the solution you'd like**
Revamp the UI for the navbar and dropdown menus to enhance clarity, ease of use, and visual appeal. This may include redesigning the layout, updating typography and color schemes, and improving the responsiveness of dropdown menus.

**Describe alternatives you've considered**
1. Simplifying the navbar structure to reduce clutter and improve readability.
2. Implementing intuitive navigation cues, such as highlighting active menu items or providing visual feedback on hover.
3. Enhancing accessibility features, such as keyboard navigation and screen reader compatibility.
4. Incorporating modern design trends and best practices to create a more cohesive and engaging user experience.

### Please assign this to me. I am gssoc'24 contributor.

**Comment by Omkar-Sonawane-23** [comment]
Duplicate 

Issue : #29
