### ISSUE TITLE
[FEAT] Dark Mode

### ISSUE THREAD

**Issue by Disha-Hati** [Omkar-Sonawane-23/VedicVani#44]
The Dark-Light Mode Toggling feature on the Top-Nav/ Header.
Can you please assign the issue to me?

**Comment by Yashaswini-raj** [comment]
Implementing a dark feature in the navbar to enhance user experience and visual appeal, utilizing either CSS or ReactJS.

Could you please assign this task to me under GSSOC'24?

**Comment by tusharyadav11** [comment]
I would like to work on this functionality. in my earlier projects i have worked on this functionality. I would be grateful if you could assign me this functionality under GSSOC'24

**Comment by Omkar-Sonawane-23** [comment]
Duplicate
