### ISSUE TITLE
Contact us page

### ISSUE THREAD

**Issue by nisargaa20** [Omkar-Sonawane-23/VedicVani#48]
**Is your feature request related to a problem? Please describe.**
Contact us page help the user to contact to the admin if there is any issue regarding the website so it will be user friendly

**Describe the solution you'd like**
Creating contact us page at the end of the footer section

Please assign me this issue under #gssoc'24

**Comment by bhavanishanker-png** [comment]
Please allocate this task to me. I'm capable of tackling it as I possess all the requisite skills to address the matter at hand.

**Comment by nisargaa20** [comment]
@bhavanishanker-png kindly raise your own issue as it is FCFS

**Comment by Omkar-Sonawane-23** [comment]
Duplicate
