### ISSUE TITLE
Home Page Css overflow problem

### ISSUE THREAD

**Issue by SayantanGhosh001** [Omkar-Sonawane-23/VedicVani#49]
The home page is not responsive. The css overflow problem happens and it shows a scroll features that's not looking good.
I want to fix this problem. Please assign me this task under #gssoc @Omkar-Sonawane-23 
The image attached below you can find the problem.
<img width="959" alt="Screenshot 2024-05-11 134853" src="https://github.com/Omkar-Sonawane-23/VedicVani/assets/97128026/46e27f9f-4bf6-4f51-89c2-ab6929e4617e">

**Comment by SayantanGhosh001** [comment]
I want to fix this problem. Can you please assign me @Omkar-Sonawane-23

**Comment by bhavanishanker-png** [comment]
Please allocate this task to me. I'm capable of tackling it as I possess all the requisite skills to address the matter at hand.

**Comment by Omkar-Sonawane-23** [comment]
Duplicate
