### ISSUE TITLE
ui improvement in home page content shloka

### ISSUE THREAD

**Issue by im-sparrow05** [Omkar-Sonawane-23/VedicVani#52]
shloka and image have insufficient space between them.
i also purpose to put sufficient space between shloka content for better user experience.

Before 
![image](https://github.com/Omkar-Sonawane-23/VedicVani/assets/108974446/6fcda013-9222-48d0-9d45-ee22b53974d5)

After 
![image](https://github.com/Omkar-Sonawane-23/VedicVani/assets/108974446/4c1bb6e7-ce1a-4aeb-92e1-aa59901b06d3)

**Comment by im-sparrow05** [comment]
i request you to assign me this issue under Gssoc'24.

**Comment by bhavanishanker-png** [comment]
Please allocate this task to me. I'm capable of tackling it as I possess all the requisite skills to address the matter at hand.
