### ISSUE TITLE
Make responsive for mobile phone

### ISSUE THREAD

**Issue by lovelyANSH2410** [Omkar-Sonawane-23/VedicVani#53]
I would like to improve the UI and make it responsive for phone too, all of the content is going outside of the screen i can fix it using Tailwind kindly assign this task to me.

**Comment by bhavanishanker-png** [comment]
Please allocate this task to me. I'm capable of tackling it as I possess all the requisite skills to address the matter at hand.

**Comment by deepak9285** [comment]
please allocate this task to me. I'm capable of tackling it as ii posses all the requisite skills to address the matter at hand

**Comment by Omkar-Sonawane-23** [comment]
Duplicate
