### ISSUE TITLE
[BUG] Content is Overflowing .

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Omkar-Sonawane-23/VedicVani#79]
**Describe the bug**
On scrolling horizontally then it is showing white blank screen .

**To Reproduce**
1. Go to Website
2. Scroll horizontally
3. You can see a white blank page .

**Expected behavior**
To be fitted inside the given width .

**Screenshots**

![Screenshot 2024-05-12 203110](https://github.com/Omkar-Sonawane-23/VedicVani/assets/118350936/5ec54c09-9d6c-43cc-b915-232cf3683f43)

**Desktop (please complete the following information):**
 - OS:Windows
 - Browser chrome
I want to work on this under GSSOC'24

**Comment by Omkar-Sonawane-23** [comment]
Duplicate
