### ISSUE TITLE
unnecessary spaces horizontally and vertically

### ISSUE THREAD

**Issue by Pratik2401** [Omkar-Sonawane-23/VedicVani#82]
**Describe the bug**
The website has unnecessary space in horizontal and vertical section and also scrollbar can be enhanced pls assign me these issue under GSSOC'24

**To Reproduce**
1. Scroll horizontally/vertically
2. See error

**Expected behavior**
Unnecessary spaces in horizontal and vertical section

**Screenshots**
![image](https://github.com/Omkar-Sonawane-23/VedicVani/assets/105542579/b75cc8ba-a8a3-4d6c-9e8d-533982446d1b)
![image](https://github.com/Omkar-Sonawane-23/VedicVani/assets/105542579/22652054-9f78-48f2-a1f8-c5a827090c11)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Comment by Omkar-Sonawane-23** [comment]
Duplicate
