### ISSUE TITLE
Adding User Login  and registration 

### ISSUE THREAD

**Issue by Mr-mahato** [Omkar-Sonawane-23/VedicVani#83]
**Is your feature request related to a problem? Please describe.**
Lets suppose that i am user of this website and i am using this website in my daily life , as this website is about vedicVani , the user will want to read continuously from where he has left . If we look now there is no any functionality that can let a user to continue reading from where he/she has left. For this we can have user login / signup page which will help us to store the user infromation.

**Describe the solution you'd like**
First i will create a login signup page using react and tailwind which will handel the frontend part , then after having the pages i will link that page with corresponding routes to the backend . And in the backend i would be using jwt , session and mongodb for storign teh user information

**Describe alternatives you've considered**
Having the login and signup page and storing the user information is the best way of solving this issue.

**Comment by Omkar-Sonawane-23** [comment]
Duplicate
