### ISSUE TITLE
not responsive

### ISSUE THREAD

**Issue by NitinChakrawarti** [Omkar-Sonawane-23/VedicVani#84]
**Describe the bug**
website is not responsive in different devices, it losses it's ui and features.

**Expected behavior**

all elemnts should adapt according to screen as user switch their device.

**Screenshots**
![Screenshot 2024-05-13 152805](https://github.com/Omkar-Sonawane-23/VedicVani/assets/149225785/9bce040d-204a-4f20-9d09-1de63cfb88b5)
![Screenshot 2024-05-13 152844](https://github.com/Omkar-Sonawane-23/VedicVani/assets/149225785/be811472-e67a-44f0-8036-ad97b2b318f0)

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [chrome]
 - Version [latest]

**Smartphone (please complete the following information):**
 - Device: [ vivo]
 - OS: [android]
 - Browser [chrome]
 

**Additional context**

website is not use friendly in mobile and different devices.

@Omkar-Sonawane-23  please assign this issue to me i am experienced in media queries, under GSSoC'24

**Comment by Omkar-Sonawane-23** [comment]
Duplicate.
