### ISSUE TITLE
Redesigning 404 error page

### ISSUE THREAD

**Issue by its-kritika** [Omkar-Sonawane-23/VedicVani#86]
A better-designed 404 error page improves user retention by reducing bounce rates through clear messaging, creativity, and opportunities for engagement. 

**Describe the solution you'd like** 
A well-designed 404 page with clear, layman-friendly language and intuitive navigation can effectively communicate that the page doesn't exist, guiding users back to the homepage for a seamless browsing experience.

![Screenshot (376)](https://github.com/Omkar-Sonawane-23/VedicVani/assets/144522556/7bd15c12-3bdf-490b-a347-c7725601e097)

To anything like this and improving it. ( This is an **SS** i have shared of my project )
![Screenshot (375)](https://github.com/Omkar-Sonawane-23/VedicVani/assets/144522556/5db6e94c-4b6b-4a2c-b29c-842af9d6769a)

Kindly assign it to me! I would be happy to contribute.

**Comment by Omkar-Sonawane-23** [comment]
Duplicate.
