### ISSUE TITLE
Uneven logo image

### ISSUE THREAD

**Issue by its-kritika** [Omkar-Sonawane-23/VedicVani#92]
**Describe the bug**
Mismatched logos in the navbar and homepage can confuse visitors, disrupting the website's visual continuity and complicating navigation, potentially leading to user disorientation and decreased site usability.

**To Reproduce**
1. Visit the webpage
2. Notice the logos

**Expected behavior**
Logo should be consistent anywhere in the website

**Screenshots**
![Screenshot (379)](https://github.com/Omkar-Sonawane-23/VedicVani/assets/144522556/ce0dedbe-192b-4e3a-a9ea-65f5dee8459b)

**Desktop (please complete the following information):**
 - Operating System: [e.g., Windows 10, macOS Big Sur]
 - Browser: [e.g., Chrome, Firefox, Safari]
 - Device: [e.g., Desktop, Laptop, Mobile]

**Additional context**
Maintaining consistency in logo presentation across a website fosters user familiarity and enhances user experience. Kindly assign it to me.

**Comment by Omkar-Sonawane-23** [comment]
@its-kritika you can start working on this.
